### ISSUE TITLE
No way to "flush" database

### ISSUE THREAD

**Issue by dector** [Jsondb/jsondb-core#39]
I'm not able to insert data in [Scratch](https://www.jetbrains.com/help/idea/scratches.html) as there is no way to force database to persist current data. Or am I missing something?

**Comment by FarooqKhan** [comment]
Every insert/update/delete to the JsonDB is done so that it's atomic. Meaning first we write to the file and only then return success. Also, we create a temp file make the write into that temp file and then do a move operation at the end. We also close all the IO Stream objects each time. So I think a explicity flush would not be required. I am not sure why you are feeling the need for a flush operation.

**Comment by dector** [comment]
Thanks for your response, @FarooqKhan !

I was using scratch files in IDEA and thought that database isn't flushing automatically.

But just now I thought that working directory for scratch files is not the same as working directory for an opened project. Will check it later and close the issue if it's actually the root of my problem. Thanks and sorry for bothering you.

**Update**. Yeah, scratches are using `$HOME` as a working dir.
