### ISSUE TITLE
Modified json file make collectionExist return false

### ISSUE THREAD

**Issue by DataMirko** [Jsondb/jsondb-core#41]
Hi!
I have 2 json db file. One for user (users.json) and one for transactions (transactions.json)
Everytime i run the java application. The transactions.json file is rewritten and i loose every data in it. 
When i add some data in the file, the jsonDBTemplate.collectionExists(Transaction.class) return false so a new transactions.json is written.

![ph](https://user-images.githubusercontent.com/50013836/90002750-5d30bd80-dc93-11ea-81e0-570ce82fa3db.jpg)

**Comment by DataMirko** [comment]
There was a mistake in the json file. Data could not loaded correctly in the java Class field

**Comment by byronv5** [comment]
Each JsonDBTemplate corresponding to dbFilesLocationString must be a singleton. Otherwise, when a second thread creates a new JsonDBTemplate(...), calling the lock method will throw an OverlappingFileLockException exception. After the exception occurs, the corresponding data item in collectionsRef will be deleted. Subsequently, when calling collectionExists, it will return false. Ultimately, if we invoke createCollection, it will overwrite the original file, resulting in data deletion.
